import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import '../globals.css';
import 'swiper/css';
import 'aos';
import 'aos/dist/aos.css';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Système de Gestion Ophtalmologie',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={`${poppins.className} w-full h-screen flex-colo bg-dry`}>
      {children}
    </div>
  );
}
