import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import 'swiper/css';
import 'aos';
import 'aos/dist/aos.css';
import 'react-tooltip/dist/react-tooltip.css';
import 'react-big-calendar/lib/css/react-big-calendar.css';
import 'react-big-calendar/lib/css/react-big-calendar.css';
import 'react-datepicker/dist/react-datepicker.css';
import 'react-modern-drawer/dist/index.css';
import Sidebar from '@/components/shared/Sidebar';
import Header from '@/components/shared/Header';
import { Toaster } from 'react-hot-toast';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Système de Gestion Ophtalmologie',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased bg-dry xl:h-screen flex-colo`}
      >
        <div className="grid xl:grid-cols-12 w-full">
          <div className="col-span-2 xl:block hidden">
            <Sidebar />
          </div>
          <div className="col-span-10 xl:h-screen overflow-y-scroll relative">
            <Header />
            <div className="xs:px-8 px-2 pt-24">
              <Toaster position="bottom-left" />
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
